# Generated by Django 4.2.1 on 2023-05-22 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('year', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_receiver', models.TextField(max_length=1000)),
                ('amount', models.CharField(max_length=256)),
                ('purpose', models.TextField(max_length=1000)),
                ('date', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('coef', models.CharField(max_length=10)),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=1000)),
                ('subjects', models.ManyToManyField(to='apis.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=1000)),
                ('parent_name', models.TextField(max_length=1000)),
                ('parent_phone', models.CharField(max_length=256)),
                ('current_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.academicyear')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.class')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=256)),
                ('sequence', models.CharField(max_length=256)),
                ('term', models.CharField(max_length=256)),
                ('average', models.CharField(max_length=256)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.student')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=256)),
                ('sequence', models.CharField(max_length=256)),
                ('term', models.CharField(max_length=256)),
                ('mark', models.CharField(max_length=256)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=256)),
                ('picture', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=256)),
                ('amount', models.CharField(max_length=256)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.academicyear')),
                ('purpose', models.ForeignKey(default='installment', on_delete=django.db.models.deletion.CASCADE, to='apis.purpose')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.student')),
            ],
        ),
    ]
