# Generated by Django 4.2.1 on 2023-05-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_purpose_paymentpurpose_alter_cashin_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOutPurpose',
            fields=[
                ('purpose', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='paymentPurpose',
        ),
    ]
