# Generated by Django 4.2.1 on 2023-06-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='owing',
            field=models.BooleanField(default=True),
        ),
    ]
